name: Fullstack Blog Continuous Integration

on:
  push:
    branches: [master]

jobs:
  test_push_request:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: ci
      PORT: 3000
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: npm run start
      - run: npm run test
