name: Fullstack Blog Continuous Integration

on:
  push:
    branches: [master]

jobs:
  test_push_request:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: ci
      PORT: 3000
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: 6.0

      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: 5
      - run: npm ci
      - run: npm run build
      - run: nohup npm run start &
      - run: npm run test
